version: '2'
services:
  mailhog:
    container_name: mail-php-todo
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    container_name: app-php-todo
    build: ./app/
    image: app-php-todo
    ports:
      - "80:80"
    depends_on:
      - mysql
      # - mailhog
    volumes:
      - ~/naokiapp/michael/todo-php-docker2:/var/www/app/
  mysql:
    container_name: mysql-php-todo
    build: ./mysql/
    image: mysql-php-todo
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: naoki
      MYSQL_PASSWORD: 11922960Kim@
      MYSQL_ROOT_PASSWORD: 11922960Kim@
      TZ: "Asia/Tokyo"
    ports:
      - "3309:3306"
    volumes:
      - ~/naokiapp/michael/todo-php-docker2/docker/docker-php-todo/mysql/db-data:/var/lib/mysql
